# role: ethpandaops.general.bootstrap
bootstrap_default_user_authorized_keys_github_team_el:
  - mariusVanDerWijden
  - holiman
  - karalabe
  - g11tech

# role: ethpandaops.general.ethereum_node
ethereum_node_el: geth

# role: ethpandaops.general.geth
geth_container_name: execution
geth_container_image: "{{ default_ethereum_client_images.geth }}"
geth_container_env:
  VIRTUAL_HOST: "{{ ethereum_node_rcp_hostname }}"
  VIRTUAL_PORT: "{{ ethereum_node_el_ports_http_rpc | string }}"
  LETSENCRYPT_HOST: "{{ ethereum_node_rcp_hostname }}"

geth_ports_ws_rpc: 8546
geth_container_ports_ipv4:
  - "127.0.0.1:{{ geth_ports_http_rpc }}:{{ geth_ports_http_rpc }}"
  - "0.0.0.0:{{ geth_ports_ws_rpc }}:{{ geth_ports_ws_rpc }}"
  - "127.0.0.1:{{ geth_ports_engine }}:{{ geth_ports_engine }}"
  - "0.0.0.0:{{ geth_ports_p2p }}:{{ geth_ports_p2p }}"
  - "0.0.0.0:{{ geth_ports_p2p }}:{{ geth_ports_p2p }}/udp"

geth_container_command_extra_args:
  - --http.api=eth,net,web3,debug,admin
  - --http.vhosts=*
  - --ws
  - --ws.addr=0.0.0.0
  - --ws.api=eth,net,web3,debug
  - --ws.port={{ geth_ports_ws_rpc }}
  - --ws.origins=*
  - --networkid={{ ethereum_network_id }}
  - --syncmode=full
  - --bootnodes={{ ethereum_el_bootnodes | join(',') }}
  - --ethstats={{ inventory_hostname }}:{{ ethstats_secret }}@{{ ethstats_url }}
geth_init_custom_network: true
geth_init_custom_network_genesis_file: "{{ eth_testnet_config_dir }}/genesis.json"
geth_init_custom_network_container_command:
  - --datadir=/data
  - init
  - /genesis.json
geth_container_pull: true

