tx_fuzz_txs_container_image: "{{ default_tooling_images.tx_fuzz }}"
tx_fuzz_txs_container_name: tx_fuzz_txs

tx_fuzz_txs_container_command:
  - spam
  - --no-al
  - --rpc=https://rpc.helder-devnets.xyz
  - --sk={{ tx_fuzz_txs_privkey }}


tx_fuzz_container_networks: "{{ docker_networks_shared }}"
