- hosts: localhost
  roles:
    - role: ethpandaops.general.ethereum_genesis
      tags: [ethereum_genesis]

- import_playbook: ethpandaops.general.bootstrap_server
  vars:
    target: "all:!localhost"
  tags: [init-server, bootstrap]

- hosts: all:!localhost
  serial: "{{ batch_count | default('100%') }}"
  become: true
  roles:
    # - role: robertdebock.fail2ban
    #   tags: [init-server, fail2ban]
    - role: geerlingguy.docker
      tags: [init-server, docker]
    - role: geerlingguy.pip
      pip_install_packages:
        - name: docker
      tags: [init-server, pip]
    - role: ethpandaops.general.docker_cleanup
      tags: [init-server, docker_cleanup]
    - role: ethpandaops.general.docker_network
      tags: [init-server, docker_network]
    - role: ethpandaops.general.node_exporter
      tags: [init-server, node_exporter]

- hosts: bootnode
  become: true
  roles:
    - role: ethpandaops.general.cl_bootnode
      tags: [cl_bootnode]
    - role: ethpandaops.general.ethereum_testnet_config
      tags: [ethereum, eth_testnet_config, ethereum_testnet_config]
    - role: ethpandaops.general.ethereum_node
      tags: [ethereum, ethereum_node]

- hosts: ethereum_node
  serial: "{{ batch_count | default('100%') }}"
  become: true
  roles:
    - role: ethpandaops.general.ethereum_testnet_config
      tags: [ethereum, eth_testnet_config, ethereum_testnet_config]
    - role: ethpandaops.general.validator_keys
      when: ethereum_node_cl_validator_enabled == true
      tags: [ethereum, validator_keys]
    - role: ethpandaops.general.ethereum_node
      tags: [ethereum, ethereum_node]
  post_tasks:
    - name: Wait between runs
      tags: [ethereum, ethereum_node]
      ansible.builtin.pause:
        seconds: >-
          {{
            batch_count is defined | ternary(
                (batch_wait_seconds | default(30)),
                0
              )
          }}

- hosts: bootnode
  become: true
  roles:
    - role: ethpandaops.general.ethereum_inventory_web
      tags: [eth_inventory_web, ethereum_inventory_web]

- hosts: dora
  become: true
  roles:
    - role: ethpandaops.general.dora
      tags: [dora]

- hosts: localhost
  roles:
    - role: ethpandaops.general.ethereum_post_network_setup
      tags: [eth_post_network_setup, ethereum_post_network_setup]
